name: onsite
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  logger: ^2.0.2+1
  pinput: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.5
  cached_network_image: ^3.3.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/
    - assets/logos/
    - assets/icons/

  fonts:
    - family: SF_Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 300